export interface Area {
  value: string;
  label: string;
  labelAr: string;
}

export interface Governorate {
  value: string;
  label: string;
  labelAr: string;
  areas: Area[];
}

export const EGYPT_GOVERNORATES: Governorate[] = [
  {
    value: "cairo",
    label: "Cairo",
    labelAr: "القاهرة",
    areas: [
      { value: "15-may", label: "15 May", labelAr: "15 مايو" },
      { value: "al-azbakeyah", label: "Al Azbakeyah", labelAr: "الازبكية" },
      { value: "al-basatin", label: "Al Basatin", labelAr: "البساتين" },
      { value: "tebin", label: "Tebin", labelAr: "التبين" },
      { value: "el-khalifa", label: "El-Khalifa", labelAr: "الخليفة" },
      { value: "el-darrasa", label: "El darrasa", labelAr: "الدراسة" },
      {
        value: "aldarb-alahmar",
        label: "Aldarb Alahmar",
        labelAr: "الدرب الاحمر",
      },
      {
        value: "zawya-al-hamra",
        label: "Zawya al-Hamra",
        labelAr: "الزاوية الحمراء",
      },
      { value: "el-zaytoun", label: "El-Zaytoun", labelAr: "الزيتون" },
      { value: "sahel", label: "Sahel", labelAr: "الساحل" },
      { value: "el-salam", label: "El Salam", labelAr: "السلام" },
      {
        value: "sayeda-zeinab",
        label: "Sayeda Zeinab",
        labelAr: "السيدة زينب",
      },
      { value: "el-sharabeya", label: "El Sharabeya", labelAr: "الشرابية" },
      { value: "shorouk", label: "Shorouk", labelAr: "مدينة الشروق" },
      { value: "el-daher", label: "El Daher", labelAr: "الظاهر" },
      { value: "ataba", label: "Ataba", labelAr: "العتبة" },
      { value: "new-cairo", label: "New Cairo", labelAr: "القاهرة الجديدة" },
      { value: "el-marg", label: "El Marg", labelAr: "المرج" },
      {
        value: "ezbet-el-nakhl",
        label: "Ezbet el Nakhl",
        labelAr: "عزبة النخل",
      },
      { value: "matareya", label: "Matareya", labelAr: "المطرية" },
      { value: "maadi", label: "Maadi", labelAr: "المعادى" },
      { value: "maasara", label: "Maasara", labelAr: "المعصرة" },
      { value: "mokattam", label: "Mokattam", labelAr: "المقطم" },
      { value: "manyal", label: "Manyal", labelAr: "المنيل" },
      { value: "mosky", label: "Mosky", labelAr: "الموسكى" },
      { value: "nozha", label: "Nozha", labelAr: "النزهة" },
      { value: "waily", label: "Waily", labelAr: "الوايلى" },
      {
        value: "bab-al-shereia",
        label: "Bab al-Shereia",
        labelAr: "باب الشعرية",
      },
      { value: "bolaq", label: "Bolaq", labelAr: "بولاق" },
      { value: "garden-city", label: "Garden City", labelAr: "جاردن سيتى" },
      {
        value: "hadayek-el-kobba",
        label: "Hadayek El-Kobba",
        labelAr: "حدائق القبة",
      },
      { value: "helwan", label: "Helwan", labelAr: "حلوان" },
      { value: "dar-al-salam", label: "Dar Al Salam", labelAr: "دار السلام" },
      { value: "shubra", label: "Shubra", labelAr: "شبرا" },
      { value: "tura", label: "Tura", labelAr: "طره" },
      { value: "abdeen", label: "Abdeen", labelAr: "عابدين" },
      { value: "abaseya", label: "Abaseya", labelAr: "عباسية" },
      { value: "ain-shams", label: "Ain Shams", labelAr: "عين شمس" },
      { value: "nasr-city", label: "Nasr City", labelAr: "مدينة نصر" },
      {
        value: "new-heliopolis",
        label: "New Heliopolis",
        labelAr: "مصر الجديدة",
      },
      {
        value: "masr-al-qadima",
        label: "Masr Al Qadima",
        labelAr: "مصر القديمة",
      },
      {
        value: "mansheya-nasir",
        label: "Mansheya Nasir",
        labelAr: "منشية ناصر",
      },
      { value: "badr-city", label: "Badr City", labelAr: "مدينة بدر" },
      { value: "obour-city", label: "Obour City", labelAr: "مدينة العبور" },
      {
        value: "cairo-downtown",
        label: "Cairo Downtown",
        labelAr: "وسط البلد",
      },
      { value: "zamalek", label: "Zamalek", labelAr: "الزمالك" },
      { value: "kasr-el-nile", label: "Kasr El Nile", labelAr: "قصر النيل" },
      { value: "rehab", label: "Rehab", labelAr: "الرحاب" },
      { value: "katameya", label: "Katameya", labelAr: "القطامية" },
      { value: "madinty", label: "Madinty", labelAr: "مدينتي" },
      { value: "rod-alfarag", label: "Rod Alfarag", labelAr: "روض الفرج" },
      { value: "sheraton", label: "Sheraton", labelAr: "شيراتون" },
      { value: "el-gamaleya", label: "El-Gamaleya", labelAr: "الجمالية" },
      {
        value: "10th-of-ramadan-city",
        label: "10th of Ramadan City",
        labelAr: "العاشر من رمضان",
      },
      {
        value: "helmeyat-alzaytoun",
        label: "Helmeyat Alzaytoun",
        labelAr: "الحلمية",
      },
      { value: "new-nozha", label: "New Nozha", labelAr: "النزهة الجديدة" },
      {
        value: "capital-new",
        label: "Capital New",
        labelAr: "العاصمة الإدارية",
      },
    ],
  },
  {
    value: "giza",
    label: "Giza",
    labelAr: "الجيزة",
    areas: [
      { value: "giza", label: "Giza", labelAr: "الجيزة" },
      {
        value: "sixth-of-october",
        label: "Sixth of October",
        labelAr: "السادس من أكتوبر",
      },
      { value: "cheikh-zayed", label: "Cheikh Zayed", labelAr: "الشيخ زايد" },
      { value: "hawamdiyah", label: "Hawamdiyah", labelAr: "الحوامدية" },
      { value: "al-badrasheen", label: "Al Badrasheen", labelAr: "البدرشين" },
      { value: "saf", label: "Saf", labelAr: "الصف" },
      { value: "atfih", label: "Atfih", labelAr: "أطفيح" },
      { value: "al-ayat", label: "Al Ayat", labelAr: "العياط" },
      { value: "al-bawaiti", label: "Al-Bawaiti", labelAr: "الباويطي" },
      {
        value: "manshiyetal-qanater",
        label: "ManshiyetAl Qanater",
        labelAr: "منشأة القناطر",
      },
      { value: "oaseem", label: "Oaseem", labelAr: "أوسيم" },
      { value: "kerdasa", label: "Kerdasa", labelAr: "كرداسة" },
      { value: "abu-nomros", label: "Abu Nomros", labelAr: "أبو النمرس" },
      { value: "kafr-ghati", label: "Kafr Ghati", labelAr: "كفر غطاطي" },
      {
        value: "manshiyet-al-bakari",
        label: "Manshiyet Al Bakari",
        labelAr: "منشأة البكاري",
      },
      { value: "dokki", label: "Dokki", labelAr: "الدقى" },
      { value: "agouza", label: "Agouza", labelAr: "العجوزة" },
      { value: "haram", label: "Haram", labelAr: "الهرم" },
      { value: "warraq", label: "Warraq", labelAr: "الوراق" },
      { value: "imbaba", label: "Imbaba", labelAr: "امبابة" },
      {
        value: "boulaq-dakrour",
        label: "Boulaq Dakrour",
        labelAr: "بولاق الدكرور",
      },
      {
        value: "al-wahat-al-baharia",
        label: "Al Wahat Al Baharia",
        labelAr: "الواحات البحرية",
      },
      { value: "omraneya", label: "Omraneya", labelAr: "العمرانية" },
      { value: "moneeb", label: "Moneeb", labelAr: "المنيب" },
      {
        value: "bin-alsarayat",
        label: "Bin Alsarayat",
        labelAr: "بين السرايات",
      },
      { value: "kit-kat", label: "Kit Kat", labelAr: "الكيت كات" },
      { value: "mohandessin", label: "Mohandessin", labelAr: "المهندسين" },
      { value: "faisal", label: "Faisal", labelAr: "فيصل" },
      { value: "abu-rawash", label: "Abu Rawash", labelAr: "أبو رواش" },
      {
        value: "hadayek-alahram",
        label: "Hadayek Alahram",
        labelAr: "حدائق الأهرام",
      },
      { value: "haraneya", label: "Haraneya", labelAr: "الحرانية" },
      {
        value: "hadayek-october",
        label: "Hadayek October",
        labelAr: "حدائق اكتوبر",
      },
      { value: "saft-allaban", label: "Saft Allaban", labelAr: "صفط اللبن" },
      {
        value: "smart-village",
        label: "Smart Village",
        labelAr: "القرية الذكية",
      },
      { value: "ard-ellwaa", label: "Ard Ellwaa", labelAr: "ارض اللواء" },
    ],
  },
  {
    value: "alexandria",
    label: "Alexandria",
    labelAr: "الأسكندرية",
    areas: [
      { value: "abu-qir", label: "Abu Qir", labelAr: "ابو قير" },
      {
        value: "al-ibrahimeyah",
        label: "Al Ibrahimeyah",
        labelAr: "الابراهيمية",
      },
      { value: "azarita", label: "Azarita", labelAr: "الأزاريطة" },
      { value: "anfoushi", label: "Anfoushi", labelAr: "الانفوشى" },
      { value: "dekheila", label: "Dekheila", labelAr: "الدخيلة" },
      { value: "el-soyof", label: "El Soyof", labelAr: "السيوف" },
      { value: "ameria", label: "Ameria", labelAr: "العامرية" },
      { value: "el-labban", label: "El Labban", labelAr: "اللبان" },
      { value: "al-mafrouza", label: "Al Mafrouza", labelAr: "المفروزة" },
      { value: "el-montaza", label: "El Montaza", labelAr: "المنتزه" },
      { value: "mansheya", label: "Mansheya", labelAr: "المنشية" },
      { value: "naseria", label: "Naseria", labelAr: "الناصرية" },
      { value: "ambrozo", label: "Ambrozo", labelAr: "امبروزو" },
      { value: "bab-sharq", label: "Bab Sharq", labelAr: "باب شرق" },
      { value: "bourj-alarab", label: "Bourj Alarab", labelAr: "برج العرب" },
      { value: "stanley", label: "Stanley", labelAr: "ستانلى" },
      { value: "smouha", label: "Smouha", labelAr: "سموحة" },
      { value: "sidi-bishr", label: "Sidi Bishr", labelAr: "سيدى بشر" },
      { value: "shads", label: "Shads", labelAr: "شدس" },
      { value: "gheet-alenab", label: "Gheet Alenab", labelAr: "غيط العنب" },
      { value: "fleming", label: "Fleming", labelAr: "فلمينج" },
      { value: "victoria", label: "Victoria", labelAr: "فيكتوريا" },
      { value: "camp-shizar", label: "Camp Shizar", labelAr: "كامب شيزار" },
      { value: "karmooz", label: "Karmooz", labelAr: "كرموز" },
      { value: "mahta-alraml", label: "Mahta Alraml", labelAr: "محطة الرمل" },
      { value: "mina-el-basal", label: "Mina El-Basal", labelAr: "مينا البصل" },
      { value: "asafra", label: "Asafra", labelAr: "العصافرة" },
      { value: "agamy", label: "Agamy", labelAr: "العجمي" },
      { value: "bakos", label: "Bakos", labelAr: "بكوس" },
      { value: "boulkly", label: "Boulkly", labelAr: "بولكلي" },
      { value: "cleopatra", label: "Cleopatra", labelAr: "كليوباترا" },
      { value: "glim", label: "Glim", labelAr: "جليم" },
      { value: "al-mamurah", label: "Al Mamurah", labelAr: "المعمورة" },
      { value: "al-mandara", label: "Al Mandara", labelAr: "المندرة" },
      { value: "moharam-bek", label: "Moharam Bek", labelAr: "محرم بك" },
      { value: "elshatby", label: "Elshatby", labelAr: "الشاطبي" },
      { value: "sidi-gaber", label: "Sidi Gaber", labelAr: "سيدي جابر" },
      {
        value: "north-coast-sahel",
        label: "North Coast/sahel",
        labelAr: "الساحل الشمالي",
      },
      { value: "alhadra", label: "Alhadra", labelAr: "الحضرة" },
      { value: "alattarin", label: "Alattarin", labelAr: "العطارين" },
      { value: "sidi-kerir", label: "Sidi Kerir", labelAr: "سيدي كرير" },
      { value: "elgomrok", label: "Elgomrok", labelAr: "الجمرك" },
      { value: "al-max", label: "Al Max", labelAr: "المكس" },
      { value: "marina", label: "Marina", labelAr: "مارينا" },
    ],
  },
  {
    value: "dakahlia",
    label: "Dakahlia",
    labelAr: "الدقهلية",
    areas: [
      { value: "mansoura", label: "Mansoura", labelAr: "المنصورة" },
      { value: "talkha", label: "Talkha", labelAr: "طلخا" },
      { value: "mitt-ghamr", label: "Mitt Ghamr", labelAr: "ميت غمر" },
      { value: "dekernes", label: "Dekernes", labelAr: "دكرنس" },
      { value: "aga", label: "Aga", labelAr: "أجا" },
      { value: "menia-el-nasr", label: "Menia El Nasr", labelAr: "منية النصر" },
      { value: "sinbillawin", label: "Sinbillawin", labelAr: "السنبلاوين" },
      { value: "el-kurdi", label: "El Kurdi", labelAr: "الكردي" },
      { value: "bani-ubaid", label: "Bani Ubaid", labelAr: "بني عبيد" },
      { value: "al-manzala", label: "Al Manzala", labelAr: "المنزلة" },
      {
        value: "tami-al-amdid",
        label: "tami al'amdid",
        labelAr: "تمي الأمديد",
      },
      { value: "aljamalia", label: "aljamalia", labelAr: "الجمالية" },
      { value: "sherbin", label: "Sherbin", labelAr: "شربين" },
      { value: "mataria", label: "Mataria", labelAr: "المطرية" },
      { value: "belqas", label: "Belqas", labelAr: "بلقاس" },
      { value: "meet-salsil", label: "Meet Salsil", labelAr: "ميت سلسيل" },
      { value: "gamasa", label: "Gamasa", labelAr: "جمصة" },
      {
        value: "mahalat-damana",
        label: "Mahalat Damana",
        labelAr: "محلة دمنة",
      },
      { value: "nabroh", label: "Nabroh", labelAr: "نبروه" },
    ],
  },
  {
    value: "red-sea",
    label: "Red Sea",
    labelAr: "البحر الأحمر",
    areas: [
      { value: "hurghada", label: "Hurghada", labelAr: "الغردقة" },
      { value: "ras-ghareb", label: "Ras Ghareb", labelAr: "رأس غارب" },
      { value: "safaga", label: "Safaga", labelAr: "سفاجا" },
      { value: "el-qusiar", label: "El Qusiar", labelAr: "القصير" },
      { value: "marsa-alam", label: "Marsa Alam", labelAr: "مرسى علم" },
      { value: "shalatin", label: "Shalatin", labelAr: "الشلاتين" },
      { value: "halaib", label: "Halaib", labelAr: "حلايب" },
      { value: "aldahar", label: "Aldahar", labelAr: "الدهار" },
    ],
  },
  {
    value: "beheira",
    label: "Beheira",
    labelAr: "البحيرة",
    areas: [
      { value: "damanhour", label: "Damanhour", labelAr: "دمنهور" },
      { value: "kafr-el-dawar", label: "Kafr El Dawar", labelAr: "كفر الدوار" },
      { value: "rashid", label: "Rashid", labelAr: "رشيد" },
      { value: "edco", label: "Edco", labelAr: "إدكو" },
      {
        value: "abu-al-matamir",
        label: "Abu al-Matamir",
        labelAr: "أبو المطامير",
      },
      { value: "abu-homs", label: "Abu Homs", labelAr: "أبو حمص" },
      { value: "delengat", label: "Delengat", labelAr: "الدلنجات" },
      { value: "mahmoudiyah", label: "Mahmoudiyah", labelAr: "المحمودية" },
      { value: "rahmaniyah", label: "Rahmaniyah", labelAr: "الرحمانية" },
      { value: "itai-baroud", label: "Itai Baroud", labelAr: "إيتاي البارود" },
      { value: "housh-eissa", label: "Housh Eissa", labelAr: "حوش عيسى" },
      { value: "shubrakhit", label: "Shubrakhit", labelAr: "شبراخيت" },
      { value: "kom-hamada", label: "Kom Hamada", labelAr: "كوم حمادة" },
      { value: "badr", label: "Badr", labelAr: "بدر" },
      { value: "wadi-natrun", label: "Wadi Natrun", labelAr: "وادي النطرون" },
      {
        value: "new-nubaria",
        label: "New Nubaria",
        labelAr: "النوبارية الجديدة",
      },
      { value: "alnoubareya", label: "Alnoubareya", labelAr: "النوبارية" },
    ],
  },
  {
    value: "fayoum",
    label: "Fayoum",
    labelAr: "الفيوم",
    areas: [
      { value: "fayoum", label: "Fayoum", labelAr: "الفيوم" },
      {
        value: "fayoum-el-gedida",
        label: "Fayoum El Gedida",
        labelAr: "الفيوم الجديدة",
      },
      { value: "tamiya", label: "Tamiya", labelAr: "طامية" },
      { value: "snores", label: "Snores", labelAr: "سنورس" },
      { value: "etsa", label: "Etsa", labelAr: "إطسا" },
      { value: "epschway", label: "Epschway", labelAr: "إبشواي" },
      {
        value: "yusuf-el-sediaq",
        label: "Yusuf El Sediaq",
        labelAr: "يوسف الصديق",
      },
      { value: "hadqa", label: "Hadqa", labelAr: "الحادقة" },
      { value: "atsa", label: "Atsa", labelAr: "اطسا" },
      { value: "algamaa", label: "Algamaa", labelAr: "الجامعة" },
      { value: "sayala", label: "Sayala", labelAr: "السيالة" },
    ],
  },
  {
    value: "gharbiya",
    label: "Gharbiya",
    labelAr: "الغربية",
    areas: [
      { value: "tanta", label: "Tanta", labelAr: "طنطا" },
      {
        value: "al-mahalla-al-kobra",
        label: "Al Mahalla Al Kobra",
        labelAr: "المحلة الكبرى",
      },
      { value: "kafr-el-zayat", label: "Kafr El Zayat", labelAr: "كفر الزيات" },
      { value: "zefta", label: "Zefta", labelAr: "زفتى" },
      { value: "el-santa", label: "El Santa", labelAr: "السنطة" },
      { value: "qutour", label: "Qutour", labelAr: "قطور" },
      { value: "basion", label: "Basion", labelAr: "بسيون" },
      { value: "samannoud", label: "Samannoud", labelAr: "سمنود" },
    ],
  },
  {
    value: "ismailia",
    label: "Ismailia",
    labelAr: "الإسماعلية",
    areas: [
      { value: "ismailia", label: "Ismailia", labelAr: "الإسماعيلية" },
      { value: "fayed", label: "Fayed", labelAr: "فايد" },
      {
        value: "qantara-sharq",
        label: "Qantara Sharq",
        labelAr: "القنطرة شرق",
      },
      {
        value: "qantara-gharb",
        label: "Qantara Gharb",
        labelAr: "القنطرة غرب",
      },
      {
        value: "el-tal-el-kabier",
        label: "El Tal El Kabier",
        labelAr: "التل الكبير",
      },
      { value: "abu-sawir", label: "Abu Sawir", labelAr: "أبو صوير" },
      {
        value: "kasasien-el-gedida",
        label: "Kasasien El Gedida",
        labelAr: "القصاصين الجديدة",
      },
      { value: "nefesha", label: "Nefesha", labelAr: "نفيشة" },
      { value: "sheikh-zayed", label: "Sheikh Zayed", labelAr: "الشيخ زايد" },
    ],
  },
  {
    value: "menofia",
    label: "Menofia",
    labelAr: "المنوفية",
    areas: [
      {
        value: "shbeen-el-koom",
        label: "Shbeen El Koom",
        labelAr: "شبين الكوم",
      },
      { value: "sadat-city", label: "Sadat City", labelAr: "مدينة السادات" },
      { value: "menouf", label: "Menouf", labelAr: "منوف" },
      { value: "sars-el-layan", label: "Sars El-Layan", labelAr: "سرس الليان" },
      { value: "ashmon", label: "Ashmon", labelAr: "أشمون" },
      { value: "al-bagor", label: "Al Bagor", labelAr: "الباجور" },
      { value: "quesna", label: "Quesna", labelAr: "قويسنا" },
      {
        value: "berkat-el-saba",
        label: "Berkat El Saba",
        labelAr: "بركة السبع",
      },
      { value: "tala", label: "Tala", labelAr: "تلا" },
      { value: "al-shohada", label: "Al Shohada", labelAr: "الشهداء" },
    ],
  },
  {
    value: "minya",
    label: "Minya",
    labelAr: "المنيا",
    areas: [
      { value: "minya", label: "Minya", labelAr: "المنيا" },
      {
        value: "minya-el-gedida",
        label: "Minya El Gedida",
        labelAr: "المنيا الجديدة",
      },
      { value: "el-adwa", label: "El Adwa", labelAr: "العدوة" },
      { value: "magagha", label: "Magagha", labelAr: "مغاغة" },
      { value: "bani-mazar", label: "Bani Mazar", labelAr: "بني مزار" },
      { value: "mattay", label: "Mattay", labelAr: "مطاي" },
      { value: "samalut", label: "Samalut", labelAr: "سمالوط" },
      {
        value: "madinat-el-fekria",
        label: "Madinat El Fekria",
        labelAr: "المدينة الفكرية",
      },
      { value: "meloy", label: "Meloy", labelAr: "ملوي" },
      { value: "deir-mawas", label: "Deir Mawas", labelAr: "دير مواس" },
      { value: "abu-qurqas", label: "Abu Qurqas", labelAr: "ابو قرقاص" },
      { value: "ard-sultan", label: "Ard Sultan", labelAr: "ارض سلطان" },
    ],
  },
  {
    value: "qaliubiya",
    label: "Qaliubiya",
    labelAr: "القليوبية",
    areas: [
      { value: "banha", label: "Banha", labelAr: "بنها" },
      { value: "qalyub", label: "Qalyub", labelAr: "قليوب" },
      {
        value: "shubra-al-khaimah",
        label: "Shubra Al Khaimah",
        labelAr: "شبرا الخيمة",
      },
      {
        value: "al-qanater-charity",
        label: "Al Qanater Charity",
        labelAr: "القناطر الخيرية",
      },
      { value: "khanka", label: "Khanka", labelAr: "الخانكة" },
      { value: "kafr-shukr", label: "Kafr Shukr", labelAr: "كفر شكر" },
      { value: "tukh", label: "Tukh", labelAr: "طوخ" },
      { value: "qaha", label: "Qaha", labelAr: "قها" },
      { value: "obour", label: "Obour", labelAr: "العبور" },
      { value: "khosous", label: "Khosous", labelAr: "الخصوص" },
      {
        value: "shibin-al-qanater",
        label: "Shibin Al Qanater",
        labelAr: "شبين القناطر",
      },
      { value: "mostorod", label: "Mostorod", labelAr: "مسطرد" },
    ],
  },
  {
    value: "new-valley",
    label: "New Valley",
    labelAr: "الوادي الجديد",
    areas: [
      { value: "el-kharga", label: "El Kharga", labelAr: "الخارجة" },
      { value: "paris", label: "Paris", labelAr: "باريس" },
      { value: "mout", label: "Mout", labelAr: "موط" },
      { value: "farafra", label: "Farafra", labelAr: "الفرافرة" },
      { value: "balat", label: "Balat", labelAr: "بلاط" },
      { value: "dakhla", label: "Dakhla", labelAr: "الداخلة" },
    ],
  },
  {
    value: "suez",
    label: "Suez",
    labelAr: "السويس",
    areas: [
      { value: "suez", label: "Suez", labelAr: "السويس" },
      { value: "alganayen", label: "Alganayen", labelAr: "الجناين" },
      { value: "ataqah", label: "Ataqah", labelAr: "عتاقة" },
      { value: "ain-sokhna", label: "Ain Sokhna", labelAr: "العين السخنة" },
      { value: "faysal", label: "Faysal", labelAr: "فيصل" },
    ],
  },
  {
    value: "aswan",
    label: "Aswan",
    labelAr: "اسوان",
    areas: [
      { value: "aswan", label: "Aswan", labelAr: "أسوان" },
      {
        value: "aswan-el-gedida",
        label: "Aswan El Gedida",
        labelAr: "أسوان الجديدة",
      },
      { value: "drau", label: "Drau", labelAr: "دراو" },
      { value: "kom-ombo", label: "Kom Ombo", labelAr: "كوم أمبو" },
      { value: "nasr-al-nuba", label: "Nasr Al Nuba", labelAr: "نصر النوبة" },
      { value: "kalabsha", label: "Kalabsha", labelAr: "كلابشة" },
      { value: "edfu", label: "Edfu", labelAr: "إدفو" },
      { value: "al-radisiyah", label: "Al-Radisiyah", labelAr: "الرديسية" },
      { value: "al-basilia", label: "Al Basilia", labelAr: "البصيلية" },
      { value: "al-sibaeia", label: "Al Sibaeia", labelAr: "السباعية" },
      {
        value: "abo-simbl-al-siyahia",
        label: "Abo Simbl Al Siyahia",
        labelAr: "ابوسمبل السياحية",
      },
      { value: "marsa-alam", label: "Marsa Alam", labelAr: "مرسى علم" },
    ],
  },
  {
    value: "assiut",
    label: "Assiut",
    labelAr: "اسيوط",
    areas: [
      { value: "assiut", label: "Assiut", labelAr: "أسيوط" },
      {
        value: "assiut-el-gedida",
        label: "Assiut El Gedida",
        labelAr: "أسيوط الجديدة",
      },
      { value: "dayrout", label: "Dayrout", labelAr: "ديروط" },
      { value: "manfalut", label: "Manfalut", labelAr: "منفلوط" },
      { value: "qusiya", label: "Qusiya", labelAr: "القوصية" },
      { value: "abnoub", label: "Abnoub", labelAr: "أبنوب" },
      { value: "abu-tig", label: "Abu Tig", labelAr: "أبو تيج" },
      { value: "el-ghanaim", label: "El Ghanaim", labelAr: "الغنايم" },
      { value: "sahel-selim", label: "Sahel Selim", labelAr: "ساحل سليم" },
      { value: "el-badari", label: "El Badari", labelAr: "البداري" },
      { value: "sidfa", label: "Sidfa", labelAr: "صدفا" },
    ],
  },
  {
    value: "beni-suef",
    label: "Beni Suef",
    labelAr: "بني سويف",
    areas: [
      { value: "bani-sweif", label: "Bani Sweif", labelAr: "بني سويف" },
      {
        value: "beni-suef-el-gedida",
        label: "Beni Suef El Gedida",
        labelAr: "بني سويف الجديدة",
      },
      { value: "al-wasta", label: "Al Wasta", labelAr: "الواسطى" },
      { value: "naser", label: "Naser", labelAr: "ناصر" },
      { value: "ehnasia", label: "Ehnasia", labelAr: "إهناسيا" },
      { value: "beba", label: "beba", labelAr: "ببا" },
      { value: "fashn", label: "Fashn", labelAr: "الفشن" },
      { value: "somasta", label: "Somasta", labelAr: "سمسطا" },
      { value: "alabbaseri", label: "Alabbaseri", labelAr: "الاباصيرى" },
      { value: "mokbel", label: "Mokbel", labelAr: "مقبل" },
    ],
  },
  {
    value: "port-said",
    label: "Port Said",
    labelAr: "بورسعيد",
    areas: [
      { value: "porsaid", label: "PorSaid", labelAr: "بورسعيد" },
      { value: "port-fouad", label: "Port Fouad", labelAr: "بورفؤاد" },
      { value: "alarab", label: "Alarab", labelAr: "العرب" },
      { value: "zohour", label: "Zohour", labelAr: "حى الزهور" },
      { value: "alsharq", label: "Alsharq", labelAr: "حى الشرق" },
      { value: "aldawahi", label: "Aldawahi", labelAr: "حى الضواحى" },
      { value: "almanakh", label: "Almanakh", labelAr: "حى المناخ" },
      { value: "mubarak", label: "Mubarak", labelAr: "حى مبارك" },
    ],
  },
  {
    value: "damietta",
    label: "Damietta",
    labelAr: "دمياط",
    areas: [
      { value: "damietta", label: "Damietta", labelAr: "دمياط" },
      {
        value: "new-damietta",
        label: "New Damietta",
        labelAr: "دمياط الجديدة",
      },
      { value: "ras-el-bar", label: "Ras El Bar", labelAr: "رأس البر" },
      { value: "faraskour", label: "Faraskour", labelAr: "فارسكور" },
      { value: "zarqa", label: "Zarqa", labelAr: "الزرقا" },
      { value: "alsaru", label: "alsaru", labelAr: "السرو" },
      { value: "alruwda", label: "alruwda", labelAr: "الروضة" },
      {
        value: "kafr-el-batikh",
        label: "Kafr El-Batikh",
        labelAr: "كفر البطيخ",
      },
      { value: "azbet-al-burg", label: "Azbet Al Burg", labelAr: "عزبة البرج" },
      {
        value: "meet-abou-ghalib",
        label: "Meet Abou Ghalib",
        labelAr: "ميت أبو غالب",
      },
      { value: "kafr-saad", label: "Kafr Saad", labelAr: "كفر سعد" },
    ],
  },
  {
    value: "sharkia",
    label: "Sharkia",
    labelAr: "الشرقية",
    areas: [
      { value: "zagazig", label: "Zagazig", labelAr: "الزقازيق" },
      {
        value: "al-ashr-men-ramadan",
        label: "Al Ashr Men Ramadan",
        labelAr: "العاشر من رمضان",
      },
      { value: "minya-al-qamh", label: "Minya Al Qamh", labelAr: "منيا القمح" },
      { value: "belbeis", label: "Belbeis", labelAr: "بلبيس" },
      {
        value: "mashtoul-el-souq",
        label: "Mashtoul El Souq",
        labelAr: "مشتول السوق",
      },
      { value: "qenaiat", label: "Qenaiat", labelAr: "القنايات" },
      { value: "abu-hammad", label: "Abu Hammad", labelAr: "أبو حماد" },
      { value: "el-qurain", label: "El Qurain", labelAr: "القرين" },
      { value: "hehia", label: "Hehia", labelAr: "ههيا" },
      { value: "abu-kabir", label: "Abu Kabir", labelAr: "أبو كبير" },
      { value: "faccus", label: "Faccus", labelAr: "فاقوس" },
      {
        value: "el-salihia-el-gedida",
        label: "El Salihia El Gedida",
        labelAr: "الصالحية الجديدة",
      },
      {
        value: "al-ibrahimiyah",
        label: "Al Ibrahimiyah",
        labelAr: "الإبراهيمية",
      },
      { value: "deirb-negm", label: "Deirb Negm", labelAr: "ديرب نجم" },
      { value: "kafr-saqr", label: "Kafr Saqr", labelAr: "كفر صقر" },
      { value: "awlad-saqr", label: "Awlad Saqr", labelAr: "أولاد صقر" },
      { value: "husseiniya", label: "Husseiniya", labelAr: "الحسينية" },
      {
        value: "san-alhajar-alqablia",
        label: "san alhajar alqablia",
        labelAr: "صان الحجر القبلية",
      },
      {
        value: "manshayat-abu-omar",
        label: "Manshayat Abu Omar",
        labelAr: "منشأة أبو عمر",
      },
    ],
  },
  {
    value: "south-sinai",
    label: "South Sinai",
    labelAr: "جنوب سيناء",
    areas: [
      { value: "al-toor", label: "Al Toor", labelAr: "الطور" },
      {
        value: "sharm-el-shaikh",
        label: "Sharm El-Shaikh",
        labelAr: "شرم الشيخ",
      },
      { value: "dahab", label: "Dahab", labelAr: "دهب" },
      { value: "nuweiba", label: "Nuweiba", labelAr: "نويبع" },
      { value: "taba", label: "Taba", labelAr: "طابا" },
      {
        value: "saint-catherine",
        label: "Saint Catherine",
        labelAr: "سانت كاترين",
      },
      { value: "abu-redis", label: "Abu Redis", labelAr: "أبو رديس" },
      { value: "abu-zenaima", label: "Abu Zenaima", labelAr: "أبو زنيمة" },
      { value: "ras-sidr", label: "Ras Sidr", labelAr: "رأس سدر" },
    ],
  },
  {
    value: "kafr-al-sheikh",
    label: "Kafr Al sheikh",
    labelAr: "كفر الشيخ",
    areas: [
      {
        value: "kafr-el-sheikh",
        label: "Kafr El Sheikh",
        labelAr: "كفر الشيخ",
      },
      {
        value: "kafr-el-sheikh-downtown",
        label: "Kafr El Sheikh Downtown",
        labelAr: "وسط البلد كفر الشيخ",
      },
      { value: "desouq", label: "Desouq", labelAr: "دسوق" },
      { value: "fooh", label: "Fooh", labelAr: "فوه" },
      { value: "metobas", label: "Metobas", labelAr: "مطوبس" },
      {
        value: "burg-al-burullus",
        label: "Burg Al Burullus",
        labelAr: "برج البرلس",
      },
      { value: "baltim", label: "Baltim", labelAr: "بلطيم" },
      { value: "masief-baltim", label: "Masief Baltim", labelAr: "مصيف بلطيم" },
      { value: "hamol", label: "Hamol", labelAr: "الحامول" },
      { value: "bella", label: "Bella", labelAr: "بيلا" },
      { value: "riyadh", label: "Riyadh", labelAr: "الرياض" },
      { value: "sidi-salm", label: "Sidi Salm", labelAr: "سيدي سالم" },
      { value: "qellen", label: "Qellen", labelAr: "قلين" },
      { value: "sidi-ghazi", label: "Sidi Ghazi", labelAr: "سيدي غازي" },
    ],
  },
  {
    value: "matrouh",
    label: "Matrouh",
    labelAr: "مطروح",
    areas: [
      { value: "marsa-matrouh", label: "Marsa Matrouh", labelAr: "مرسى مطروح" },
      { value: "el-hamam", label: "El Hamam", labelAr: "الحمام" },
      { value: "alamein", label: "Alamein", labelAr: "العلمين" },
      { value: "dabaa", label: "Dabaa", labelAr: "الضبعة" },
      { value: "al-nagila", label: "Al-Nagila", labelAr: "النجيلة" },
      { value: "sidi-brani", label: "Sidi Brani", labelAr: "سيدي براني" },
      { value: "salloum", label: "Salloum", labelAr: "السلوم" },
      { value: "siwa", label: "Siwa", labelAr: "سيوة" },
      { value: "marina", label: "Marina", labelAr: "مارينا" },
      { value: "north-coast", label: "North Coast", labelAr: "الساحل الشمالى" },
    ],
  },
  {
    value: "luxor",
    label: "Luxor",
    labelAr: "الأقصر",
    areas: [
      { value: "luxor", label: "Luxor", labelAr: "الأقصر" },
      { value: "new-luxor", label: "New Luxor", labelAr: "الأقصر الجديدة" },
      { value: "esna", label: "Esna", labelAr: "إسنا" },
      { value: "new-tiba", label: "New Tiba", labelAr: "طيبة الجديدة" },
      { value: "al-ziynia", label: "Al ziynia", labelAr: "الزينية" },
      { value: "al-bayadieh", label: "Al Bayadieh", labelAr: "البياضية" },
      { value: "al-qarna", label: "Al Qarna", labelAr: "القرنة" },
      { value: "armant", label: "Armant", labelAr: "أرمنت" },
      { value: "al-tud", label: "Al Tud", labelAr: "الطود" },
    ],
  },
  {
    value: "qena",
    label: "Qena",
    labelAr: "قنا",
    areas: [
      { value: "qena", label: "Qena", labelAr: "قنا" },
      { value: "new-qena", label: "New Qena", labelAr: "قنا الجديدة" },
      { value: "abu-tesht", label: "Abu Tesht", labelAr: "ابو طشت" },
      { value: "nag-hammadi", label: "Nag Hammadi", labelAr: "نجع حمادي" },
      { value: "deshna", label: "Deshna", labelAr: "دشنا" },
      { value: "alwaqf", label: "Alwaqf", labelAr: "الوقف" },
      { value: "qaft", label: "Qaft", labelAr: "قفط" },
      { value: "naqada", label: "Naqada", labelAr: "نقادة" },
      { value: "farshout", label: "Farshout", labelAr: "فرشوط" },
      { value: "quos", label: "Quos", labelAr: "قوص" },
    ],
  },
  {
    value: "north-sinai",
    label: "North Sinai",
    labelAr: "شمال سيناء",
    areas: [
      { value: "arish", label: "Arish", labelAr: "العريش" },
      { value: "sheikh-zowaid", label: "Sheikh Zowaid", labelAr: "الشيخ زويد" },
      { value: "nakhl", label: "Nakhl", labelAr: "نخل" },
      { value: "rafah", label: "Rafah", labelAr: "رفح" },
      { value: "bir-al-abed", label: "Bir al-Abed", labelAr: "بئر العبد" },
      { value: "al-hasana", label: "Al Hasana", labelAr: "الحسنة" },
    ],
  },
  {
    value: "sohag",
    label: "Sohag",
    labelAr: "سوهاج",
    areas: [
      { value: "sohag", label: "Sohag", labelAr: "سوهاج" },
      {
        value: "sohag-el-gedida",
        label: "Sohag El Gedida",
        labelAr: "سوهاج الجديدة",
      },
      { value: "akhmeem", label: "Akhmeem", labelAr: "أخميم" },
      {
        value: "akhmim-el-gedida",
        label: "Akhmim El Gedida",
        labelAr: "أخميم الجديدة",
      },
      { value: "albalina", label: "Albalina", labelAr: "البلينا" },
      { value: "el-maragha", label: "El Maragha", labelAr: "المراغة" },
      { value: "almunsha-a", label: "almunsha'a", labelAr: "المنشأة" },
      { value: "dar-aisalaam", label: "Dar AISalaam", labelAr: "دار السلام" },
      { value: "gerga", label: "Gerga", labelAr: "جرجا" },
      {
        value: "jahina-al-gharbia",
        label: "Jahina Al Gharbia",
        labelAr: "جهينة الغربية",
      },
      { value: "saqilatuh", label: "Saqilatuh", labelAr: "ساقلته" },
      { value: "tama", label: "Tama", labelAr: "طما" },
      { value: "tahta", label: "Tahta", labelAr: "طهطا" },
      { value: "alkawthar", label: "Alkawthar", labelAr: "الكوثر" },
    ],
  },
];

export function getAreasForGovernorate(governorateValue: string): Area[] {
  return (
    EGYPT_GOVERNORATES.find((g) => g.value === governorateValue)?.areas ?? []
  );
}
